### PR TITLE
Update aphrodite 1 -> 2, remove aphrodite dependency from interface package

### PR DESCRIPTION
**Pull request by lencioni**
No changes should be required for this package.

Also, I'm not sure if this dependency is required for the interface
since I don't see it imported there. I posted a comment about it here:

https://github.com/airbnb/react-with-styles-interface-css/commit/36085c1b8509878f8eaf28a0565db743b317d5eb#r28844818

### CODE REVIEW

**Comment by lencioni** [comment]
Should it even be a dependency of the interface?

**Comment by ljharb** [comment]
Also, I agree - the interface does *not* need it as a dep.

**Comment by lencioni** [comment]
@ljharb I've removed it from the interface now. I suppose we could add it to the compiler as a peerDep, but not sure that really matters since it is just a compiler. PTAL

**Comment by ljharb** [comment]
It should still be a peerDep of the compiler, to prevent duplicates, but nbd.

**Comment by majapw** [comment]
Weird! it's possible that i was confused when I was splitting up the code. :) Thank you for cleaning this up!

**Pull request merged**
